### ISSUE TITLE
Gogen Crud shared/infrastructure/server not found

### ISSUE THREAD

**Issue by imaman15** [mirzaakhena/gogen#13]
return &controller{
		UsecaseRegisterer: gogen.NewBaseController(),
		ControllerStarter: server.NewGracefullyShutdown(log, router, address),
		Router:            router,
		log:               log,
		cfg:               cfg,
		jwtToken:          jwtToken,
	}

di situ manggil file shared/infrastructure/server/gracefully_shutdown.go

sedangkan folder server tidak ada ketika saya lakukan command gogen crud 

di dalam folder \gogen\shared\infrastructure hanya ada :
- cache
- database
- logger
- messaging
- remoting
- token

jadi ketika di run dapat eror :
domain_test\controller\userapi\controller.go:8:2: package test/shared/infrastructure/server is not in std (C:\Program Files\Go\src\test\shared\infrastructure\server)

**Comment by mirzaakhena** [comment]
Terimakasih ya atas laporan issuenya.
Sudah difix. di versi v0.0.23

bisa coba ini utk install yg versi baru
```
$ go install -v github.com/mirzaakhena/gogen@v0.0.23
```

**Comment by mirzaakhena** [comment]
fixed https://github.com/mirzaakhena/gogen/releases/tag/v0.0.23

**Comment by imaman15** [comment]
<img width="960" alt="image" src="https://github.com/mirzaakhena/gogen/assets/28895905/e7f93a14-8b11-4924-9af6-65ae7f7f23a6">


saya sudah install versi terbaru lalu di code saya yang sudah jalan saya coba gogen crud lgi tapi shared server tidak ada.
apakah harus create lagi dari awal project nya ?

sementara saya akali seperti ini

<img width="960" alt="image" src="https://github.com/mirzaakhena/gogen/assets/28895905/c07d2045-1629-4915-b2ba-ec10347c8b7c">

**Comment by mirzaakhena** [comment]
Folder shared server itu memang tidak dipakai lagi di controller.
Idealnya memang bikin ulang, tapi kalau sudah terlanjur panjang, coba aj tes bikin project baru di direktori lain. lihat perubahannya apa saja. As long as it works, nothing to worry 👌🏼
