### ISSUE TITLE
Bug with `gogen error` Command

### ISSUE THREAD

**Issue by raismaulana** [mirzaakhena/gogen#6]
i tried to create error enum using `gogen error ...`, its successfully created the enum in `apperror/error_enum.go` but in the terminal produced `2021/08/12 10:30:19 cmd.Run() failed with exec: "goimports": executable file not found in $PATH`

screenshot:

1.  terminal
![image](https://user-images.githubusercontent.com/22321111/129134453-5b7d7143-d4c7-4fff-8258-31c9d51950ca.png)
2. apperror/error_enum.go
![image](https://user-images.githubusercontent.com/22321111/129134590-fab186da-de3c-4205-ae3d-f83fc1029576.png)

**Comment by mirzaakhena** [comment]
gogen use goimports to reformat the code, insert dependency import to code, and arrange import alphabetical.
You need to make sure your your system have this goimports apps.

```
$ which goimports
/Users/mirza/go/bin/goimports
```

**Comment by raismaulana** [comment]
Thanks, I install goimports `go get golang.org/x/tools/cmd/goimports` and no error anymore.
