### ISSUE TITLE
Bug `gogen controller controllername UsecaseName` Command

### ISSUE THREAD

**Issue by raismaulana** [mirzaakhena/gogen#7]
I tried to create controller using `gogen controller restapi CreateUser` and it produced an error `ERROR : open usecase/CreateUser/inport.go: no such file or directory`.
This is happening because when creating usecase using gogen command will generate lowcase directory name.
When i tried `gogen controller restapi createuser`, it's success

screenshot:
1. error
![image](https://user-images.githubusercontent.com/22321111/129221630-d94b1cde-2496-430b-9f40-513030008d8e.png)
2. directory structure
![image](https://user-images.githubusercontent.com/22321111/129221792-36e14a75-7559-4076-ba29-119fc60a5a67.png)

**Comment by raismaulana** [comment]
maybe you can update the readme in this part https://github.com/mirzaakhena/gogen#create-a-controller-for-your-usecase

**Comment by mirzaakhena** [comment]
How do you generate the CreateUser usecase?
is it 
```
gogen usecase CreateUser
```
or
```
gogen usecase createuser
```
?

Currently usecase name is case sensitive. So you need to use it as is when call controller or gateway or registry. 
But i think in the next version when user want to generate controller, gateway or registry, it does not have to be case sensitive.

**Comment by raismaulana** [comment]
> How do you generate the CreateUser usecase?

I used PascalCase `gogen usecase CreateUser`

I think the problem is `gogen controller` tries to read `usecase/CreateUser/inport.go` while the right directory is `usecase/createuser/inport.go`.

Imo, just lower case the `UsecaseName` at https://github.com/mirzaakhena/gogen/blob/master/gogencommand/controller.go line 315, you can change it with `fileReadPath := fmt.Sprintf("usecase/%s/inport.go", strings.ToLower(obj.UsecaseName))`.

**Comment by mirzaakhena** [comment]
Ahh yes.. you right. I already fix it.
