### ISSUE TITLE
Hi. It's very nice~!. I have a question.

### ISSUE THREAD

**Issue by YoungsoonLee** [mirzaakhena/gogen#8]
Hi. It's very nice~!. I have a question.
How to do test or make a mock??

**Comment by mirzaakhena** [comment]
You can make a test by creating the usecase first. For example
```
gogen usecase RegisterUser
```

After you finish work on the RegisterUser usecase, then you can call
```
gogen test RegisterUser
```

the tools will help you create the test file. Previously i use mockery for making a mock. But i think we need to back to the nature of golang simplicity by just implement the whole thing (implement the outport interface) directly in a test file.

**Comment by YoungsoonLee** [comment]
Great~! 
It would be better if you update this content in the README.
Thanks~!
